Public Class AllClass
    Public Shared Property ОплатыПер As List(Of ОплатыПер)
    Public Shared Property ОтчетРаботыСотрудника As List(Of ОтчетРаботыСотрудника)
    Public Shared Property ОтчетРаботыСотрудникаСводная As List(Of ОтчетРаботыСотрудникаСводная)
    Public Shared Property ОплатыКлиент As List(Of ОплатыКлиент)
    Public Shared Property РейсыПеревозчика As List(Of РейсыПеревозчика)
    Public Shared Property Перевозчики As List(Of Перевозчики)
    Public Shared Property ФормаСобств As List(Of ФормаСобств)
    Public Shared Property РейсыКлиента As List(Of РейсыКлиента)
    Public Shared Property Клиент As List(Of Клиент)
    Public Shared Property ТипАвто As List(Of ТипАвто)
    Public Shared Property ГрузыКлиентов As List(Of ГрузыКлиентов)
    Public Shared Property Календарь_Даты As List(Of Календарь_Даты)
    Public Shared Property ПереговорыКлиент As List(Of ПереговорыКлиент)
    Public Shared Property КалендарьНапоминание As List(Of КалендарьНапоминание)
    Public Shared Property Пароли As List(Of Пароли)
    Public Shared Property ЖурналДата As List(Of ЖурналДата)
    Public Shared Property ЖурналКлиентГруз As List(Of ЖурналКлиентГруз)
    Public Shared Property ЖурналКлиентМаршрут As List(Of ЖурналКлиентМаршрут)
    Public Shared Property ЖурналКлиентСписок As List(Of ЖурналКлиентСписок)
    Public Shared Property РегионыРоссии As List(Of РегионыРоссии)
    Public Shared Property Страна As List(Of Страна)
    Public Shared Property ЖурналПеревозчик As List(Of ЖурналПеревозчик)
    Public Shared Property ПеревозчикиБаза As List(Of ПеревозчикиБаза)
    Public Shared Property ФайлыExcelВсе As List(Of ФайлыExcelВсе)
    Public Shared Property ПаролиВвод As List(Of ПаролиВвод)
    Public Shared Property SkypeКлиентПредложение As List(Of SkypeКлиентПредложение)
    Public Shared Property SkypeПеревозчикПредложение As List(Of SkypeПеревозчикПредложение)
    Public Shared Property КалендарьРезультатЗвонка As List(Of КалендарьРезультатЗвонка)
    Public Shared Property ЖурналКлиентДаты As List(Of ЖурналКлиентДаты)
    Public Shared Property ЖурналПеревозчикСобытия As List(Of ЖурналПеревозчикСобытия)
    Public Shared Property ЧерныйСписок As List(Of ЧерныйСписок)
    Public Shared Property СводнаяОплаты As List(Of СводнаяОплаты)
    Public Shared Property СводнаяОплатыТаблицы As List(Of СводнаяОплатыТаблицы)



End Class
