<?xml version="1.0" encoding="utf-8"?><Database Name="Rickmans" Class="dbAllDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=178.124.211.175,52891;Initial Catalog=Rickmans;Persist Security Info=True;User ID=Rickmans" SettingsObjectName="Грузы.My.MySettings" SettingsPropertyName="RickmansConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Клиент" Member="Клиент">
    <Type Name="Клиент">
      <Column Name="НазваниеОрганизации" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Форма собственности]" Member="Форма_собственности" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Адрес организации]" Member="Адрес_организации" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Почтовый адрес]" Member="Почтовый_адрес" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="РасчСчетРубли" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="РасчСчетРоссРубли" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="РасчСчетДоллар" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="РасчСчетЕвро" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Адрес банка]" Member="Адрес_банка" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Контактное лицо]" Member="Контактное_лицо" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Телефон" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Договор" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Дата" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Должность" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="НаОснЧегоДейств" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ФИОРуководителя" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДогСНерез" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="СтарыеДанные" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ПорНомРейса" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ФИОРодПадеж" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДолжРодПадеж" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Клиент_РейсыКлиента" Member="РейсыКлиента" ThisKey="НазваниеОрганизации" OtherKey="НазвОрганизации" Type="РейсыКлиента" />
    </Type>
  </Table>
  <Table Name="dbo.ФормаСобств" Member="ФормаСобств">
    <Type Name="ФормаСобств">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ПолноеНазвание" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Сокращенное" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ТипАвто" Member="ТипАвто">
    <Type Name="ТипАвто">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ТипАвто" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Перевозчики" Member="Перевозчики">
    <Type Name="Перевозчики">
      <Column Name="Названиеорганизации" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Форма собственности]" Member="Форма_собственности" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Адрес организации]" Member="Адрес_организации" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Почтовый адрес]" Member="Почтовый_адрес" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="РасчСчетРубли" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="РасчСчетРоссРубли" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="РасчСчетДоллар" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="РасчСчетЕвро" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Адрес банка]" Member="Адрес_банка" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Контактное лицо]" Member="Контактное_лицо" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Телефон" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Договор" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Дата" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Должность" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="НаОснЧегоДейств" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ФИОРуководителя" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДогСНерез" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="СтарыеДанные" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ПорНомРейса" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ФИОРодпадеж" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ПерЭкспедитор" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДолжРодПадеж" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Перевозчики_РейсыПеревозчика" Member="РейсыПеревозчика" ThisKey="Названиеорганизации" OtherKey="НазвОрганизации" Type="РейсыПеревозчика" />
    </Type>
  </Table>
  <Table Name="dbo.ГрузыКлиентов" Member="ГрузыКлиентов">
    <Type Name="ГрузыКлиентов">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Организация" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Дата" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Груз" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="СтранаЗагрузки" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="СтранаВыгрузки" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ГородЗагрузки" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ГородВыгрузки" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ставка" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="регионЗагрузки" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Экспедитор" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="СтавкаПеревозу" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Состояние" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДляСкайпа" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ОрганизКонтакт" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.КалендарьНапоминание" Member="КалендарьНапоминание">
    <Type Name="КалендарьНапоминание">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ДатаНапоминания" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ВремяНапоминания" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ТекстНапоминания" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Пользователь" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ПереговорыКлиент" Member="ПереговорыКлиент">
    <Type Name="ПереговорыКлиент">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Клиент" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаПереговоров" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ТекстПереговора" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ДатаНапоминания" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ТекстНапоминания" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="КонтДанные" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Экспедитор" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ОЧемДоговорВсплывФорма" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ДатаОчемДоговорилис" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Календарь_Даты" Member="Календарь_Даты">
    <Type Name="Календарь_Даты">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Дата" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="[0.00]" Member="_0_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[1.00]" Member="_1_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[2.00]" Member="_2_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[3.00]" Member="_3_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[4.00]" Member="_4_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[5.00]" Member="_5_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[6.00]" Member="_6_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[7.00]" Member="_7_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[8.00]" Member="_8_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[9.00]" Member="_9_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[10.00]" Member="_10_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[11.00]" Member="_11_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[12.00]" Member="_12_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[13.00]" Member="_13_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[14.00]" Member="_14_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[15.00]" Member="_15_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[16.00]" Member="_16_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[17.00]" Member="_17_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[18.00]" Member="_18_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[19.00]" Member="_19_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[20.00]" Member="_20_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[21.00]" Member="_21_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[22.00]" Member="_22_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[23.00]" Member="_23_00" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Выполнение" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ОтчетРаботыСотрудника" Member="ОтчетРаботыСотрудника">
    <Type Name="ОтчетРаботыСотрудника">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Год" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Месяц" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ОтчетРаботыСотрудника_ОтчетРаботыСотрудникаСводная" Member="ОтчетРаботыСотрудникаСводная" ThisKey="ID" OtherKey="IDОтчетРабСотрудн" Type="ОтчетРаботыСотрудникаСводная" />
    </Type>
  </Table>
  <Table Name="dbo.ОплатыКлиент" Member="ОплатыКлиент">
    <Type Name="ОплатыКлиент">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDКлиента" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Рейс" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ДатаОплаты" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Сумма" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="РейсыКлиента_ОплатыКлиент" Member="РейсыКлиента" ThisKey="IDКлиента" OtherKey="Код" Type="РейсыКлиента" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.ОплатыПер" Member="ОплатыПер">
    <Type Name="ОплатыПер">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDПер" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Рейс" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ДатаОплаты" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Сумма" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="РейсыПеревозчика_ОплатыПер" Member="РейсыПеревозчика" ThisKey="IDПер" OtherKey="Код" Type="РейсыПеревозчика" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.РейсыПеревозчика" Member="РейсыПеревозчика">
    <Type Name="РейсыПеревозчика">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="НазвОрганизации" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="НомерРейса" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="КоличРейсов" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Маршрут" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаПодачиПодЗагрузку" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ВремяПодачи" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаПодачиПодРастаможку" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ВремяПодачиВыгРаст" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ТочныйАдресЗагрузки" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="АдресЗатаможки" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="НаименованиеГруза" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ТипТрСредства" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="НомерАвтомобиля" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Водитель" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ТочнАдресРаста" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ТочнАдресРазгр" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="СтоимостьФрахта" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Валюта" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ВалютаПлатежа" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="СрокОплаты" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДопУсловия" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ДогПор" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДогПорЭксп" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаПоручения" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ПорЭксп" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ПоИнотерр" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ПоТеррРБ" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаАкта" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="НомерСМР" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="УсловияОплаты" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаПолученияДоков" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ДатаОплаты" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ОстатокОплаты" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="РазмерШтрафаЗаСрыв" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Предоплата" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="СрывЗагр20Проц" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Экспедитор" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаСоздания" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="РейсыПеревозчика_ОплатыПер" Member="ОплатыПер" ThisKey="Код" OtherKey="IDПер" Type="ОплатыПер" />
      <Association Name="Перевозчики_РейсыПеревозчика" Member="Перевозчики" ThisKey="НазвОрганизации" OtherKey="Названиеорганизации" Type="Перевозчики" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.РейсыКлиента" Member="РейсыКлиента">
    <Type Name="РейсыКлиента">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="НазвОрганизации" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="НомерРейса" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="КоличРейсов" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Маршрут" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаПодачиПодЗагрузку" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ВремяПодачи" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаПодачиПодРастаможку" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ВремяПодачиВыгРаст" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ТочныйАдресЗагрузки" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="АдресЗатаможки" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="НаименованиеГруза" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ТипТрСредства" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="НомерАвтомобиля" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Водитель" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ТочнАдресРаста" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ТочнАдресРазгр" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="СтоимостьФрахта" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Валюта" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ВалютаПлатежа" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="СрокОплаты" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДопУсловия" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ДогПор" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДогПорЭксп" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаПоручения" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ПорЭксп" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ПоИнотерр" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ПоТеррРБ" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаАкта" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="НомерСМР" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ЗаявкаКлиента" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="НомерЗаявки" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ДатаЗаявки" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="УсловияОплаты" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Год" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ДатаОтправкиДоков" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ДатаОплаты" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ОстатокОплаты" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="РазмерШтрафаЗаСрыв" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Предоплата" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ОплатаПоКурсу" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ОплатаПоКурсуКурс" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Экспедитор" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ДатаСоздания" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="РейсыКлиента_ОплатыКлиент" Member="ОплатыКлиент" ThisKey="Код" OtherKey="IDКлиента" Type="ОплатыКлиент" />
      <Association Name="Клиент_РейсыКлиента" Member="Клиент" ThisKey="НазвОрганизации" OtherKey="НазваниеОрганизации" Type="Клиент" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.ОтчетРаботыСотрудникаСводная" Member="ОтчетРаботыСотрудникаСводная">
    <Type Name="ОтчетРаботыСотрудникаСводная">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDОтчетРабСотрудн" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="счет" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="заказчик" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Загрузка" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Выгрузка" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ДатаЗагрузки" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ДатаВыгрузки" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ВалютаЗак" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="КурсЗак" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ИтогоЗакБелРуб" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ДатаОплатыЗак" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Перевозчик" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ВалютаПер" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="КурсПер" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ИтогоПерБелРуб" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="КомиссияЗаПеревод" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="СтрахованиеГруза" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ДатаОплатыПер" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Дельта" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ИтогоОбщая" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ИтогоСотрудник" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Экспедитор" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ДатаСоздания" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ОтчетРаботыСотрудника_ОтчетРаботыСотрудникаСводная" Member="ОтчетРаботыСотрудника" ThisKey="IDОтчетРабСотрудн" OtherKey="ID" Type="ОтчетРаботыСотрудника" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Пароли" Member="Пароли">
    <Type Name="Пароли">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Логин" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Парол" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ЖурналДата" Member="ЖурналДата">
    <Type Name="ЖурналДата">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Дата" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="ЖурналДата_ЖурналКлиентГруз" Member="ЖурналКлиентГруз" ThisKey="Код" OtherKey="КодЖурналДата" Type="ЖурналКлиентГруз" />
    </Type>
  </Table>
  <Table Name="dbo.ЖурналКлиентМаршрут" Member="ЖурналКлиентМаршрут">
    <Type Name="ЖурналКлиентМаршрут">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="КодЖурналКлиентГруз" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Клиент" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="СтранаПогрузки" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="СтранаВыгрузки" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ГородПогрузки" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ГородВыгрузки" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="КвадратПогрузки" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="КвадратВыгрузки" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ТаможняОтправления" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ТаможняНазначения" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ставка" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EX" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ДополнитИнформация" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ЖурналКлиентГруз_ЖурналКлиентМаршрут" Member="ЖурналКлиентГруз" ThisKey="КодЖурналКлиентГруз" OtherKey="Код" Type="ЖурналКлиентГруз" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.ЖурналКлиентСписок" Member="ЖурналКлиентСписок">
    <Type Name="ЖурналКлиентСписок">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Клиент" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="КонтактноеЛицо" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Телефон" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ЖурналКлиентГруз" Member="ЖурналКлиентГруз">
    <Type Name="ЖурналКлиентГруз">
      <Column Name="Код" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="КодЖурналДата" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Клиент" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="НаименованиеГруза" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Вес" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Обьем" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Длина" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ширина" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Высота" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ТипПогрузки" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ПаллетыШтук" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="РазмерПаллет" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ADR" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ДополнитИнформация" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ДатаЗагрузки" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ДатаВыгрузки" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ТипАвто" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="ЖурналКлиентГруз_ЖурналКлиентМаршрут" Member="ЖурналКлиентМаршрут" ThisKey="Код" OtherKey="КодЖурналКлиентГруз" Type="ЖурналКлиентМаршрут" />
      <Association Name="ЖурналДата_ЖурналКлиентГруз" Member="ЖурналДата" ThisKey="КодЖурналДата" OtherKey="Код" Type="ЖурналДата" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>